### ISSUE TITLE
How to handle two objs of the same type in the EntityMapper

### ISSUE THREAD

**Issue by iamgmd** [landmarkhw/Dapper.GraphQL#2]
I am having trouble when trying to map two of the same model type in my entity mapper. Is there a way to handle this?

**Model**

public class Account
{
    public Guid AccountId { get; set; }
    public string Name { get; set; }
    public Contact PrimaryContact { get; set; }
    public Contact SecondaryContact { get; set; }
}

**EntityMapper**

public class AccountEntityMapper :
        IEntityMapper<Account>
    {
        public Func<Account, Account> ResolveEntity { get; set; }
        public Account Map(IEnumerable<object> objs)
        {
            Account account = null;
            foreach (var obj in objs)
            {
                if (obj is Account p)
                {
                    account = ResolveEntity(p);
                    continue;
                }
                if (obj is Contact primaryContact)
                {
                    account.PrimaryContact = primaryContact;
                    continue;
                }
                if (obj is Contact secondaryContact)
                {
                    account.SecondaryContact = secondaryContact;
                    continue;
                }
            }
            return account;
        }
    }

**Comment by dougrday** [comment]
I'm working on a solution to this with code examples, it would require an upgrade to a later version.

Stay tuned.

**Comment by iamgmd** [comment]
Excellent dougrday, looking forward to it.

**Comment by iamgmd** [comment]
Hi dougrday, any news on this implementation? it's currently a blocker for my project.

**Comment by dougrday** [comment]
I'll see if I can get the implementation pushed up to github in the next couple of days, with code examples.  I'm having trouble getting SQLite to play nice with it (the in-memory implementation doesn't appear to support this kind of situation), but other providers should work.

**Comment by dougrday** [comment]
This has been fixed in release 0.2.0-beta, and is available on NuGet.  Sorry for the wait.

**Comment by dougrday** [comment]
@iamgmd You should be unblocked, please let me know if the implementation doesn't provide the functionality you need.  See here for examples:

https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/QueryBuilders/PersonQueryBuilder.cs (line 55)
https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/GraphQL/PersonQuery.cs (line 29)
https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/EntityMappers/PersonEntityMapper.cs (line 44)
