### ISSUE TITLE
More complex project examples

### ISSUE THREAD

**Issue by nunogois** [landmarkhw/Dapper.GraphQL#20]
Hi, I'm trying to implement Dapper.GraphQL and streamline the process of adding our several models.

The existing examples are great but I'm having a bit of difficulty on understanding how to put the pieces together when considering several models in a big project. Based on the existing examples, is it possible to have a single Schema for all of our queries, for example? If not, how should I properly DI them into my single GraphQL controller? The example seems a bit locked on PersonSchema.

Also, should I just assume we'll need an EntityMapper, Query, QueryBuilder, Schema, Type and Model for each Model in our business logic, from which we manually add each Type, Query, Schema and QueryBuilder to DapperGraphQL options on services configuration @ Startup.cs? Would that be best practice? Is there any way to do so dynamically?

Some hints would be greatly appreciated!

**Comment by dougrday** [comment]
> Based on the existing examples, is it possible to have a single Schema for all of our queries, for example?

Yes.  You can certainly have a single schema and query, and have as many operations based on that as needed.  In our more complex projects, that's how it's setup.

> Also, should I just assume we'll need an EntityMapper, Query, QueryBuilder, Schema, Type and Model for each Model in our business logic, from which we manually add each Type, Query, Schema and QueryBuilder to DapperGraphQL options on services configuration @ Startup.cs?

This sounds correct.

> Would that be best practice?

As this is such a new library, best practices are evolving.  But, as it stands, that's the best way to do it.

> Is there any way to do so dynamically?

This could be a good idea for a new feature.  It would certainly make managing the DI environment easier (e.g. no more "ah heck, I forgot to add it to DI")

**Comment by nunogois** [comment]
Thank you @dougrday, your input was exactly what I was looking for.

**Comment by dougrday** [comment]
I'll be adding more complex examples to the project as part of this issue.  Stay tuned...

**Comment by nunogois** [comment]
Great! Looking forward to it.

**Comment by dougrday** [comment]
@nunogois OK, I've implemented some more complex examples.

It includes:

1. Entity deduplication at the database level (see [MergedToPersonId in Person.cs](https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/Models/Person.cs#L15) and [PersonQueryBuilder.cs](https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/QueryBuilders/PersonQueryBuilder.cs#L31)).
2. Association tables that _are not_ part of the entity mapping process (see [PersonQueryBuilder.cs](https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/QueryBuilders/PersonQueryBuilder.cs#L49)).
3. Note that entity mapping has recently improved significantly (see [PersonEntityMapper.cs](https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/EntityMappers/PersonEntityMapper.cs)).
