### ISSUE TITLE
How to implement a Many to Many relationship

### ISSUE THREAD

**Issue by iamgmd** [landmarkhw/Dapper.GraphQL#24]
How does one go about implementing a many to many relationship using a through table? Do we have an example? i.e. Do I have to create an entity mapper/builder for the through table or is there a way to go from source entity to destination entity?

**Comment by dougrday** [comment]
You can implement a many-to-many relationship using an association table -- this is done in the unit tests like this:

**SQL** -- [https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/Sql/1-Create.sql](https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/Sql/1-Create.sql)

```
CREATE TABLE Person (
	Id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	MergedToPersonId INTEGER,
	FirstName VARCHAR(50),
	LastName VARCHAR(50),
	SupervisorId INTEGER,
	CareerCounselorId INTEGER,
	FOREIGN KEY (MergedToPersonId) REFERENCES Person(Id),
	FOREIGN KEY (SupervisorId) REFERENCES Person(Id),
	FOREIGN KEY (CareerCounselorId) REFERENCES Person(Id)
);

CREATE TABLE Email (
	Id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Address VARCHAR(250)
);

CREATE TABLE PersonEmail (
	Id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	PersonId INTEGER NOT NULL,
	EmailId INTEGER NOT NULL,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(EmailId) REFERENCES Email(Id)
);
```

**QueryBuilder** - [https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/QueryBuilders/PersonQueryBuilder.cs#L58](https://github.com/landmarkhw/Dapper.GraphQL/blob/master/Dapper.GraphQL.Test/QueryBuilders/PersonQueryBuilder.cs#L58)

```
            if (fields.ContainsKey("emails"))
            {
                var personEmailAlias = $"{alias}PersonEmail";
                var emailAlias = $"{alias}Email";
                // Join twice here to handle the many-to-many relationship
                query
                    .LeftJoin($"PersonEmail {personEmailAlias} ON {mergedAlias}.Id = {personEmailAlias}.PersonId")
                    .LeftJoin($"Email {emailAlias} ON {personEmailAlias}.EmailId = {emailAlias}.Id");
                query = emailQueryBuilder.Build(query, fields["emails"], emailAlias);
            }
```
