### ISSUE TITLE
graphql-dotnet 2.0

### ISSUE THREAD

**Issue by narbit** [landmarkhw/Dapper.GraphQL#29]
Was wondering if there's a timeline for upgrading graphql-dotnet to 2.x? I understand there's one breaking change but it sounds like @benmccallum was able to work around it. Any other reasons to not move forward with it?

**Comment by dougrday** [comment]
Nope, just whether it fits into the timelines of contributors :)  At the moment, I'm pretty buried in deadlines that aren't related to this library.  If anyone wants to take a stab at it (I bet it isn't that difficult), please feel free.

**Comment by dougrday** [comment]
Thanks for the contribution.  I'll get 0.4.0-beta released ASAP :)

**Comment by dougrday** [comment]
This is included in the 0.4.0-beta release, which I just finished publishing.  Happy coding!

**Comment by narbit** [comment]
Doug, I've just updated Dapper.GraphQL package in my project and still seeing old GraphQL version after update. Uninstalled it and installed from scratch just to be sure. No luck. Nuget hiccup?


![image](https://user-images.githubusercontent.com/2797543/47380060-6cefa400-d6b1-11e8-91bd-eb31af54aa71.png)

**Comment by dougrday** [comment]
@narbit Apologies, my fault - I missed a pretty important git merge step :)   I've updated it to version 0.4.1-beta, which should now have your PRs.  Please let me know if you run into any more issues!

Thanks!
