### ISSUE TITLE
SqlQueryContext.GetSplitOnTypes() missing in nuget release

### ISSUE THREAD

**Issue by benmccallum** [landmarkhw/Dapper.GraphQL#6]
I'm just building up a basic solution with the example docs and this method isn't resolving from me. Doesn't look like it's in the nuget released assembly. Thanks!

**Comment by dougrday** [comment]
Try getting the beta version.  The 0.1 version is prerelease, but wasn't marked as such in NuGet.

**Comment by benmccallum** [comment]
Ahh yep, there it is. Thanks! It's probably worth just hiding that mistaken release if you don't want people on it. You can do that through the nuget portal so it won't appear in searches/package manager.

**Comment by dougrday** [comment]
Didn't know that - I'll disable that when I get a few minutes, thanks.
